name: Update to latest Calibre Release

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          ./update.sh
